config/routes.rb
Rails.application.routes.draw do
  resources :books, only: [:show, :index] do
    collection do
      get '/alpha', to: 'books#alpha'
    end
    member do
      get '/author', to: 'books#author'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def alpha
    @books = Book.all.select { |book| book.title.start_with?(params[:alpha]) }
  end

  def show
    @book = Book.find(params[:id])
  end

  def author
    @author = Book.find(params[:id]).author
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/alpha.html.erb
<h1> Book tites starting with letter <%= params[:alpha] %> </h1>

<ul>
  <% @books.each do |book| %>
    <%= link_to book_path(book) do %>
      <li> <%= book.title %> </li>
    <% end %>
  <% end %>
</ul>

app/views/books/author.html.erb
<h3>This is the author page! </h3>

<p> Name of the author: <%= @author %></p>

<p class="text-muted"> Lorem, ipsum dolor sit amet consectetur adipisicing elit. Esse, vel tempore dolorum velit reprehenderit non dolor consectetur assumenda, nulla ducimus quasi numquam quibusdam earum fuga corrupti iste qui nihil suscipit maxime nesciunt nam aperiam ratione a. Quas, est autem? Omnis similique suscipit modi nam cupiditate? </p>

app/views/books/index.html.erb
<h3> These are all my books </h3>

<ul>
  <% @books.each do |book| %>
    <%= link_to book_path(book) do %>
      <li> <%= book.title %> </li>
    <% end %>
  <% end %>
</ul>


<p> Find book by title: </p>
<% ("A".."Z").each do |letter| %>
  <%= link_to letter, alpha_books_path(alpha: letter ) %>
<% end %>

app/views/books/show.html.erb
<h4> <%= @book.title %> </h4>
<p class="text-muted"> By <%= @book.author %> </p class="text-muted">
<%= "This book was written by #{@book.author}" %>

<p> Learn more about <%= link_to "the author", author_book_path(@book) %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemberVsCollectionsBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-5">
     <%= yield %>
    </div>
  </body>
</html>